### ISSUE TITLE
How to deal with multiple await blocks?

### ISSUE THREAD

**Issue by robsontenorio** [kentor/flush-promises#13]
```js
  async mounted () {
    try {
      this.users = await getUsers()
      this.countries = await getCounties()
    } catch (error) {
      this.erro = error
    }
```

**Comment by kentor** [comment]
I would need more context to tell what you're doing. How are you using this in a test?

**Comment by robsontenorio** [comment]
Just noticed it only fails on Gitlab CI (pipeline). Local works fine. I can’t find anything related. 

Thanks for your time.
