### ISSUE TITLE
The principles the library works

### ISSUE THREAD

**Issue by Yvour** [kentor/flush-promises#26]
I have googled a lot and found some people asking why and how this library works.
It would be very useful to add the comment here with some advices of usage.
For example for correct usage all setTimeout/setIntervals and lodash's debounce-like functions should be mocked with direct execution.

**Comment by Maxim-Mazurok** [comment]
I think it has something to do with how the async loop works in JS, some basics are explained here: https://www.youtube.com/watch?v=vn3tm0quoqE

**Comment by kentor** [comment]
See https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/
